#################################
# Backend & General Settings
#################################
backend = "glx";
vsync = true;
log-level = "warn";
unredir-if-possible = true;

#################################
# Fading
#################################
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 10;
no-fading-openclose = false;

#################################
# Transparency
#################################
inactive-opacity = 0.9;
active-opacity = 1;
opacity-rule = [
  "90:class_g = 'Alacritty'"]
#################################
# Blur
#################################
blur-method = "dual_kawase";
blur-strength = 3;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
